app1/urls.py
from django.urls import path
from . import views

app_name='app1'
urlpatterns=[
    path('',views.MemberListView.as_view(),name='index'),
    path('add-member',views.MemberCreateView.as_view(),name='add-member'),
    path('<int:pk>/update',views.MemberUpadateView.as_view(),name='update-member'),
    path('<int:pk>/delete',views.MemberDeleteView.as_view(),name='delete-member'),
]

first_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),

]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app1/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.
class Member(models.Model):
    name=models.CharField(max_length=40)
    age=models.IntegerField()
    nationality=models.CharField(max_length=40)
    primary=models.CharField(max_length=40)
    secondary=models.CharField(max_length=40)
    email=models.EmailField()
    occupation=models.CharField(max_length=40)
    slogan=models.CharField(max_length=50)
    residence=models.CharField(max_length=40)
    photo=models.ImageField()
    campus=models.CharField(max_length=40)
    course=models.CharField(max_length=40)
    hobby=models.CharField(max_length=40)
    is_male=models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('app1:index')

app1/views.py
from django.shortcuts import render
from .models import Member
from django.views.generic import ListView,CreateView,UpdateView,DeleteView

# Create your views here.
class MemberListView(ListView):
    model = Member
    template_name = 'app1/index.html'
    context_object_name = 'profiles'
    ordering = ['name']

    def get_queryset(self):
        query=self.request.GET.get('q')
        if query:
            return Member.objects.filter(name__icontains=query) | Member.objects.filter( occupation__icontains=query)
        else:
            return Member.objects.all()

class MemberCreateView(CreateView):
    model = Member
    fields = '__all__'

class MemberUpadateView(UpdateView):
    model = Member
    fields = '__all__'

class MemberDeleteView(DeleteView):
    model = Member
    success_url = '/'

app1/templates/app1/base.html
<html lang="en">
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<!--<link href='https://fonts.googleapis.com/css?family=Cabin Sketch' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Bree Serif' rel='stylesheet'>-->
<link href='https://fonts.googleapis.com/css?family=Gugi' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Lora' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Orbitron' rel='stylesheet'>



{% load static %}
<link rel="stylesheet" href="{% static 'app1/css/style.css' %}" type="text/css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{% url 'app1:index' %}" style="font-family: 'Acme', cursive;">PYTHON MEMBERS</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
    <li class="nav-item">
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ request.GET.q }}">
      <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
    </form>
        </li>
    </ul>
    <ul class="navbar-nav">
        <li class="nav-item active">
      <a class="nav-link" href="{% url 'app1:add-member' %}" style="font-family: 'Orbirton', cursive;"><i class="fas fa-user-plus" style="color: steelblue;"></i> Add Member<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
      <a class="nav-link" href="" style="font-family: 'Orbirton', cursive;"><i class="fas fa-sign-out-alt" style="color: red;"></i> Logout<span class="sr-only">(current)</span></a>
      </li>

    </ul>
  </div>
</nav>
<div class="container">

    {% block content %}

    {% endblock %}


</div>



</body>

app1/templates/app1/index.html
{% extends 'app1/base.html' %}
{% block title %} Python Members {% endblock %}
{% block content %}
    <div class="row">
            {% if profiles %}
               {% for prof in profiles  %}
                  <div class="col-sm-3">
                      <div class="card card-body my-1" style="background-color: {% if prof.is_male %}orange; {% else %}pink; {% endif %}">
                          <h4 class="text-center"
                              style="white-space: nowrap;
                                     overflow: hidden;
                                     text-overflow: ellipsis;
                                     max-width: 90%;
                                     font-family: Gugi">{{prof.name}}</h4>
                          <hr>
                          <img src="{{prof.photo.url}}" class="rounded-circle mx-auto img-fluid" alt="" style="height:150px; width:150px;">
                          <div class="caption">
                              <h5 class="text-center"
                                  style="white-space: nowrap;
                                         overflow: hidden;
                                         text-overflow: ellipsis;
                                         max-width: 90%;
                                         font-family: Orbitron">{{prof.occupation}}</h5>
                              <h6 class="text-center"
                                  style="white-space: nowrap;
                                         overflow: hidden;
                                         text-overflow: ellipsis;
                                         max-width: 90%;
                                         font-family: Pacifico">{{prof.slogan}}</h6>
                              <button class="btn btn-info btn-sm" data-toggle="modal" data-target="#modal-{{prof.id}}">
                                  <i class="fas fa-info"></i>
                              </button>
                              <a href="{% url 'app1:delete-member' prof.id %}" class="btn btn-danger btn-sm" style="float: right;"><i class="fas fa-trash"></i></a>
                          </div>
                      </div>
                      <!--modal-->
                      <div class="modal fade modal-md" id="modal-{{prof.id}}" role="dialog">
                          <div class="modal-dialog">
                               <div class="modal-content">
                                  <div class="modal-header">
                                      <h4 class="modal-title" style="font-family: Pacifico">{{prof.name}}</h4>
                                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                                  </div>
                                  <div class="modal-body">
                                      <p style="font-family: Lora">
                                          {{prof.name}} is {{prof.age}} years old. {% if prof.is_male %} He {% else %} She {% endif %} is a Kenyan Citizen.
                                          {% if prof.is_male %} He {% else %} She {% endif %} went to {{prof.primary}} and later joined {{prof.secondary}}.
                                          {{prof.name}} is a {{prof.occupation}} by profession. {% if prof.is_male %} He {% else %} She {% endif %} lives in
                                          {{prof.residence}}. You can easily reach {% if prof.is_male %} him {% else %} her {% endif %} via the email:<a href="mailto:{{prof.email}}">{{prof.email}}</a> .
                                          {% if prof.is_male %} His {% else %} Her {% endif %} slogan is {{prof.slogan}}. {% if prof.is_male %} He {% else %} She {% endif %}
                                          is currently pursuing {{prof.course}} at {{prof.campus}}. {% if prof.is_male %} His {% else %} Her {% endif %} hobby is {{prof.hobby}}.

                                      </p>
                                  </div>
                                  <div class="modal-footer">
                                      <a href="{%url 'app1:update-member' prof.id %}" class="btn btn-outline-primary btn-sm"><i class="fas fa-edit"></i></a>
                                  </div>
                                </div>
                          </div>
                      </div>
                  </div>
               {% endfor %}
            {% endif %}
     </div>
{% endblock %}

app1/templates/app1/member_confirm_delete.html
{% extends 'app1/base.html' %}
{% block title %} Delete Member {% endblock %}
{% block content %}
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <div class="card card-body my-1">
                <h3>Delete <b>{{object.name}}</b>?</h3>
                <hr>
                <form method="post" class="form-horizontal">
                    {% csrf_token %}
                    <div class="form-group">
                        <button type="submit" class="btn btn-danger">Delete</button>
                        <a href="{% url 'app1:index'%}" class="btn btn-secondary">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app1/templates/app1/member_form.html
{% extends 'app1/base.html' %}
{% block title %}{% if object %}Update {{object.name}} {%else%} Add Member {%endif%} {% endblock %}
{% block content %}
{%load crispy_forms_tags%}


    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <div class="card card-body my-1">
                <h3 class="text-capitalize">{% if object %} Update {{object.name}} {%else%} Add member {%endif%}</h3>
                <hr>
                <form method="post" enctype="multipart/form-data">
                    {%csrf_token%}
                    {{form|crispy}}

                    <div class="form-group">
                        <button type="submit" class="btn btn-info">{% if object %} Update {%else%} Submit {%endif%}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}